"use strict";

// prettier-ignore
const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

const form = document.querySelector(".form");
const containerWorkouts = document.querySelector(".workouts");
const inputType = document.querySelector(".form__input--type");
const inputDistance = document.querySelector(".form__input--distance");
const inputDuration = document.querySelector(".form__input--duration");
const inputCadence = document.querySelector(".form__input--cadence");
const inputElevation = document.querySelector(".form__input--elevation");

// let map, mapEvent;

class Workout {
  date = new Date();
  id = (new Date().getTime() + "").slice(-10);

  constructor(coords, distance, duration) {
    this.coords = coords;
    this.distance = distance; // in km
    this.duration = duration; // in min
  }
}

class Running extends Workout {
  name = "running";

  constructor(coords, distance, duration, cadence) {
    super(coords, distance, duration);
    this.cadence = cadence;
    this.calcPace();
  }

  calcPace() {
    //    min/km
    this.pace = this.duration / this.distance;
    return this.pace;
  }
}

class Cycling extends Workout {
  name = "cycling";

  constructor(coords, distance, duration, elevationGain) {
    super(coords, distance, duration);
    this.elevationGain = elevationGain;
    this.calcSpeed();
  }

  calcSpeed() {
    //    km/h
    this.speed = this.distance / (this.duration / 60);
    return this.speed;
  }
}

class App {
  #map;
  #mapEvent;

  constructor() {
    this._getPosition();

    form.addEventListener("submit", this._newWorkout.bind(this));

    inputType.addEventListener("change", this._toggleElevationField);
  }

  _getPosition() {
    /**
     *  !   "navigator.geolocation" is the geolocation API provided by the browser
     */
    if (navigator.geolocation) {
      //*   it is to check wether "navigator.geolocation" is present in the browser
      /**
       *  ! SYNTAX --->   navigator.geolocation.getCurrentPosition(successCallback, errorCallback)
       */
      navigator.geolocation.getCurrentPosition(
        this._loadMap.bind(this),
        function () {
          alert("Could not get your position :(");
        }
      );
    }
  }

  _loadMap(position) {
    const { latitude } = position.coords;
    const { longitude } = position.coords;

    // //   console.log(latitude, longitude);
    // //   console.log(`https://www.google.com/maps/@${latitude},${longitude}`);

    const coords = [latitude, longitude];

    /**
     *  !  It is the main function that leaflet uses as an entry point (it is kinda like an entry point)
     *  ! "L" is the main object provided by leaflet, it is used to make markers, map etc.
     */
    this.#map = L.map("map").setView(coords, 14); //  .setView([latitude, longitude], zoomLevel)

    L.tileLayer("https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png", {
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(this.#map);

    /**
     *  Since, only the map knows the coordinates of the position clicked on the map. That's why, instead of browser's event listener method, we are using ".on" method provided by leaflet library itself
     *
     * ?  "mapEvent" is the event generated by "on" method, it is different from the "events" generated by regular ".addEventListener" method
     */
    this.#map.on("click", this._showForm.bind(this));
  }

  _showForm(mapE) {
    this.#mapEvent = mapE;

    form.classList.remove("hidden");
    inputDistance.focus();
    // // console.log(mapEvent);
  }

  _toggleElevationField() {
    inputCadence.closest(".form__row").classList.toggle("form__row--hidden");
    inputElevation.closest(".form__row").classList.toggle("form__row--hidden");
  }

  _newWorkout(e) {
    e.preventDefault();

    //  clearing input values
    inputDistance.value =
      inputDuration.value =
      inputCadence.value =
      inputElevation.value =
        "";

    const { lat, lng } = this.#mapEvent.latlng;

    //*   used to add marker
    L.marker([lat, lng], {
      riseOnHover: true,
      riseOffset: 300,
    })
      .addTo(this.#map)
      .bindPopup(
        L.popup({
          maxWidth: 250,
          minWidth: 100,
          autoClose: false, //  used both the options because pop-ups close by default when another pop-up is open
          closeOnClick: false,
          className: "running-popup",
        })
      )
      .setPopupContent("Workout")
      .openPopup();
  }
}

const app = new App();

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//!  ********************** MY FIRST ATTEMPT

// if (navigator.geolocation) {
//   navigator.geolocation.getCurrentPosition(
//     function (position) {
//       const { latitude } = position.coords;
//       const { longitude } = position.coords;

//       //   console.log(latitude, longitude);
//       //   console.log(`https://www.google.com/maps/@${latitude},${longitude}`);

//       const coords = [latitude, longitude];

//       const map = L.map("map").setView(coords, 14);
//       // console.log(map);

//       L.tileLayer("https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png", {
//         attribution:
//           '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
//       }).addTo(map);

//       let workoutType = "running";
//       let lat, lng;

//       /////////////
//       const renderFromLocalStorage = function () {
//         if (localStorage.length > 0) {
//           for (const key in localStorage) {
//             if (Object.hasOwnProperty.call(localStorage, key)) {
//               const workoutData = JSON.parse(localStorage[key]);
//               console.log(JSON.parse(localStorage[key]).timeStamp);

//               L.marker([workoutData.lat, workoutData.lng])
//                 .addTo(map)
//                 .bindPopup(
//                   L.popup({
//                     maxWidth: 250,
//                     minWidth: 100,
//                     autoClose: false,
//                     closeOnClick: false,
//                     className: `${workoutData.workoutType}-popup`,
//                   })
//                 )
//                 .setPopupContent(
//                   `${
//                     workoutData.workoutType === "running"
//                       ? "🏃‍♂️ Running"
//                       : "🚴‍♀️ Cycling"
//                   } on ${new Date(workoutData.timeStamp).getDate()} ${
//                     months[new Date(workoutData.timeStamp).getMonth()]
//                   }`
//                 )
//                 .openPopup();

//               const html =
//                 workoutData.workoutType === "running"
//                   ? `<li class="workout workout--running" data-id='${
//                       workoutData.timeStamp
//                     }'>
//                   <h2 class="workout__title">Running on April 14</h2>
//                   <div class="workout__details">
//                     <span class="workout__icon">🏃‍♂️</span>
//                     <span class="workout__value">${workoutData.distance}</span>
//                     <span class="workout__unit">km</span>
//                   </div>

//                   <div class="workout__details">
//                     <span class="workout__icon">⏱</span>
//                     <span class="workout__value">${workoutData.duration}</span>
//                     <span class="workout__unit">min</span>
//                   </div>

//                   <div class="workout__details">
//                     <span class="workout__icon">⚡️</span>
//                     <span class="workout__value">${(
//                       workoutData.duration / workoutData.distance
//                     ).toFixed(2)}</span>
//                     <span class="workout__unit">min/km</span>
//                   </div>

//                   <div class="workout__details">
//                     <span class="workout__icon">🦶🏼</span>
//                     <span class="workout__value">${workoutData.cadence}</span>
//                     <span class="workout__unit">spm</span>
//                   </div>
//                 </li>`
//                   : `<li class="workout workout--cycling" data-id='${
//                       workoutData.timeStamp
//                     }'>
//                     <h2 class="workout__title">Cycling on April 5</h2>
//                     <div class="workout__details">
//                       <span class="workout__icon">🚴‍♀️</span>
//                       <span class="workout__value">${
//                         workoutData.distance
//                       }</span>
//                       <span class="workout__unit">km</span>
//                     </div>
//                     <div class="workout__details">
//                       <span class="workout__icon">⏱</span>
//                       <span class="workout__value">${
//                         workoutData.duration
//                       }</span>
//                       <span class="workout__unit">min</span>
//                     </div>
//                     <div class="workout__details">
//                       <span class="workout__icon">⚡️</span>
//                       <span class="workout__value">${(
//                         workoutData.distance / workoutData.duration
//                       ).toFixed(2)}</span>
//                       <span class="workout__unit">km/h</span>
//                     </div>
//                     <div class="workout__details">
//                       <span class="workout__icon">⛰</span>
//                       <span class="workout__value">${
//                         workoutData.elevation
//                       }</span>
//                       <span class="workout__unit">m</span>
//                     </div>
//                   </li>`;

//               containerWorkouts.insertAdjacentHTML("beforeend", html);
//             }
//           }
//         }
//       };
//       renderFromLocalStorage();
//       ///////////////

//       map.on("click", function (mapEvent) {
//         //  1.  display form on click
//         form.classList.remove("hidden");

//         lat = mapEvent.latlng.lat;
//         lng = mapEvent.latlng.lng;
//       });

//       //  2.  alter results on changing workout type
//       inputType.addEventListener("change", function (e) {
//         if (e.target.value === "running") {
//           workoutType = "running";

//           inputCadence
//             .closest(".form__row")
//             .classList.remove("form__row--hidden");
//           inputElevation
//             .closest(".form__row")
//             .classList.add("form__row--hidden");
//         } else if (e.target.value === "cycling") {
//           workoutType = "cycling";

//           inputCadence.closest(".form__row").classList.add("form__row--hidden");
//           inputElevation
//             .closest(".form__row")
//             .classList.remove("form__row--hidden");
//         }
//       });

//       //  3.  on submit, preventdefault, hide form
//       form.addEventListener("submit", function (e) {
//         e.preventDefault();

//         const workoutData = {
//           lat,
//           lng,
//           workoutType,
//           timeStamp: Date.now(),
//           distance: Number(inputDistance.value),
//           duration: Number(inputDuration.value),
//           cadence: workoutType === "running" ? Number(inputCadence.value) : " ",
//           elevation: Number(inputElevation.value || 0),
//         };

//         if (
//           workoutData.distance &&
//           workoutData.duration &&
//           workoutData.cadence
//         ) {
//           //  4.  add workout to list and a pin on map
//           L.marker([workoutData.lat, workoutData.lng])
//             .addTo(map)
//             .bindPopup(
//               L.popup({
//                 maxWidth: 250,
//                 minWidth: 100,
//                 autoClose: false,
//                 closeOnClick: false,
//                 // `${workoutType}-popup`
//                 className: `${workoutData.workoutType}-popup`,
//                 // content: "No Workout",
//               })
//             )
//             .setPopupContent(
//               `${
//                 workoutData.workoutType === "running"
//                   ? "🏃‍♂️ Running"
//                   : "🚴‍♀️ Cycling"
//               } on ${new Date(workoutData.timeStamp).getDate()} ${
//                 months[new Date(workoutData.timeStamp).getMonth()]
//               }`
//             )
//             .openPopup();

//           const html =
//             workoutData.workoutType === "running"
//               ? `<li class="workout workout--running" data-id='${
//                   workoutData.timeStamp
//                 }'>
//             <h2 class="workout__title">Running on April 14</h2>
//             <div class="workout__details">
//               <span class="workout__icon">🏃‍♂️</span>
//               <span class="workout__value">${workoutData.distance}</span>
//               <span class="workout__unit">km</span>
//             </div>

//             <div class="workout__details">
//               <span class="workout__icon">⏱</span>
//               <span class="workout__value">${workoutData.duration}</span>
//               <span class="workout__unit">min</span>
//             </div>

//             <div class="workout__details">
//               <span class="workout__icon">⚡️</span>
//               <span class="workout__value">${(
//                 workoutData.duration / workoutData.distance
//               ).toFixed(2)}</span>
//               <span class="workout__unit">min/km</span>
//             </div>

//             <div class="workout__details">
//               <span class="workout__icon">🦶🏼</span>
//               <span class="workout__value">${workoutData.cadence}</span>
//               <span class="workout__unit">spm</span>
//             </div>
//           </li>`
//               : `<li class="workout workout--cycling" data-id='${
//                   workoutData.timeStamp
//                 }'>
//               <h2 class="workout__title">Cycling on April 5</h2>
//               <div class="workout__details">
//                 <span class="workout__icon">🚴‍♀️</span>
//                 <span class="workout__value">${workoutData.distance}</span>
//                 <span class="workout__unit">km</span>
//               </div>
//               <div class="workout__details">
//                 <span class="workout__icon">⏱</span>
//                 <span class="workout__value">${workoutData.duration}</span>
//                 <span class="workout__unit">min</span>
//               </div>
//               <div class="workout__details">
//                 <span class="workout__icon">⚡️</span>
//                 <span class="workout__value">${(
//                   workoutData.distance / workoutData.duration
//                 ).toFixed(2)}</span>
//                 <span class="workout__unit">km/h</span>
//               </div>
//               <div class="workout__details">
//                 <span class="workout__icon">⛰</span>
//                 <span class="workout__value">${workoutData.elevation}</span>
//                 <span class="workout__unit">m</span>
//               </div>
//             </li>`;

//           containerWorkouts.insertAdjacentHTML("afterbegin", html);

//           inputDistance.value =
//             inputDuration.value =
//             inputCadence.value =
//             inputElevation.value =
//               "";

//           localStorage.setItem(
//             "workoutData",
//             localStorage.getItem("workoutData") + JSON.stringify(workoutData)
//           );

//           //  5.  hide form
//           form.classList.add("hidden");
//         } else {
//           alert("All the inputs need to positive numbers.");
//         }
//       });
//     },
//     function () {
//       alert("Could not get your position :(");
//     }
//   );
// }
